### ISSUE TITLE
[Feature Request] Ignore a set of namespaces and specific pods

### ISSUE THREAD

**Issue by ventsislav-georgiev** [airwallex/k8s-pod-restart-info-collector#1]
Thanks for the great tool!

In my case there are some system pods from DaemonSets which get expected restarts while the Node is still being initialized.
Will be useful to have a way to ignore a set of namespaces or even better specific pods via label selector.

**Comment by able8** [comment]
Thanks for your feedback.
We will add a way to ignore some namespaces and some pods via label selector within one week.
