### ISSUE TITLE
watchNamespaces instead of ignoredNamespaces

### ISSUE THREAD

**Issue by mst1711** [airwallex/k8s-pod-restart-info-collector#14]
Hi
I think more usable watchNamespaces instead of ignoreNamespaces. We can append or drop some NS and after this, we should update config of collector. Can you append this work mode of the collector watch only listed NS?
Or when collector work without clusterrole, only in one NS.

**Comment by olfway** [comment]
May be name it "namespaces" and "podNamePrefixes" ?
