### ISSUE TITLE
Why alert on less than 30 restarts?

### ISSUE THREAD

**Issue by zrks** [airwallex/k8s-pod-restart-info-collector#15]
Hi, wanted to understand whether there is specific reason why pods with restart count larger than 30 are ignored?
Relevant code - https://github.com/airwallex/k8s-pod-restart-info-collector/blob/master/controller.go#L67

Could we make this configurable?

Thanks!

**Comment by springwell** [comment]
I'm not sure. But I created PR to make this configurable.
Feel free to use it if you need it soon.

https://github.com/airwallex/k8s-pod-restart-info-collector/pull/12

**Comment by able8** [comment]
Thanks.  I will create a new release and make this configurable.

**Comment by able8** [comment]
Merged https://github.com/airwallex/k8s-pod-restart-info-collector/pull/18/files
