### ISSUE TITLE
[Feature Request] Support Existing Secret

### ISSUE THREAD

**Issue by reefland** [airwallex/k8s-pod-restart-info-collector#2]
Within the `values.yaml` I would like to be able to reference a pre-existing secret to define my variables (I set them via a secrets manager for encryption/gitops).  Something like how Grafana allows it:

`existingSecret: "kube-prometheus-stack-grafana"`

**Comment by lucass4** [comment]
@able8  I can take this one if you are ok with it.
 This is the same scenario I have; hardcoding the slack URL is not an option.

**Comment by able8** [comment]
You can take it.  Thanks @lucass4 .
