### ISSUE TITLE
[Feature Request] Flag to turn off alerts for exit code 0

### ISSUE THREAD

**Issue by csheppard00** [airwallex/k8s-pod-restart-info-collector#22]
Hello,

I am seeing a lot of slack messages from the service for restarts with exit code 0. Can we get an option to disable posting for exit code 0?

Thank you.

**Comment by unitrade** [comment]
Yes, we have a lot of slack messages from the service with exit code 0 too.
Please, add this option ti disable this.
Thank you

**Comment by jeremych1000** [comment]
100% needs to happen - woke up to 200 messages in our Slack today all with exit code 0 😂

**Comment by able8** [comment]
We have added this feature, see https://github.com/airwallex/k8s-pod-restart-info-collector/blob/master/CHANGELOG.md#130---2023-05-11
